on:  
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g minify
      - run: |
          shopt -s globstar
          for f in assets/**/*.css
          do
            minify $f > $f.min
            mv $f.min $f
          done
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
